# Generated by Django 3.1.3 on 2021-01-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('address', models.CharField(default='', max_length=512)),
                ('price', models.CharField(default='', max_length=100)),
                ('tags', models.CharField(default='', max_length=100)),
                ('property_type', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('bedrooms', models.CharField(default='', max_length=100)),
                ('bathrooms', models.CharField(default='', max_length=100)),
                ('halls', models.CharField(default='', max_length=100)),
                ('kitchens', models.CharField(default='', max_length=100)),
                ('area', models.CharField(default='', max_length=100)),
                ('property_id', models.CharField(default='', max_length=100)),
                ('year_built', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('lot_dimensions', models.CharField(default='', max_length=100)),
                ('deposit_amount', models.CharField(default='', max_length=100)),
                ('is_fav', models.BooleanField(default=False)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('images', models.CharField(default=False, max_length=512)),
                ('about_builder', models.CharField(default=False, max_length=512)),
                ('financial', models.CharField(default=False, max_length=512)),
                ('due_diligence', models.CharField(default=False, max_length=512)),
                ('property_details', models.CharField(default=False, max_length=512)),
                ('updates', models.CharField(default=False, max_length=512)),
                ('doc_reports', models.CharField(default=False, max_length=512)),
                ('location', models.CharField(default=False, max_length=512)),
                ('map_location', models.CharField(default=False, max_length=512)),
                ('location_detail', models.CharField(default=False, max_length=1024)),
                ('localty', models.CharField(default=False, max_length=100)),
                ('storeys', models.CharField(default=False, max_length=100)),
                ('parking', models.CharField(default=False, max_length=100)),
                ('floor_of_sale', models.CharField(default=False, max_length=100)),
                ('parking_ratio', models.CharField(default=False, max_length=100)),
                ('floor_efficiency', models.CharField(default=False, max_length=100)),
                ('fit_outs', models.CharField(default=False, max_length=100)),
                ('total_area', models.CharField(default=False, max_length=100)),
                ('power_area', models.CharField(default=False, max_length=100)),
                ('power_backup', models.CharField(default=False, max_length=100)),
                ('area_of_sale', models.CharField(default=False, max_length=100)),
                ('air_conditioning', models.CharField(default=False, max_length=100)),
                ('purchase_price', models.CharField(default=False, max_length=100)),
                ('stamp_duty', models.CharField(default=False, max_length=100)),
                ('brokerage', models.CharField(default=False, max_length=100)),
                ('legal_fees', models.CharField(default=False, max_length=100)),
                ('reserves', models.CharField(default=False, max_length=100)),
                ('highlights', models.CharField(default=False, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
