# Generated by Django 3.1.3 on 2021-01-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210128_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='media/document')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
