# Generated by Django 3.1.3 on 2021-01-28 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210128_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured_image10',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image2',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image3',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image4',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image5',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image6',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image7',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image8',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AddField(
            model_name='property',
            name='featured_image9',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='homely/static/media/featured_image'),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
