# Generated by Django 3.1.3 on 2021-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210128_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image10',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image7',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image8',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image9',
            field=models.ImageField(blank=True, null=True, upload_to='media/featured_image'),
        ),
    ]
