# Generated by Django 3.1.3 on 2021-01-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210128_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='floor_of_sale',
            new_name='floor_for_sale',
        ),
    ]
