# Generated by Django 3.1.3 on 2021-01-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210128_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='financial_desclaimer',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
