# Generated by Django 3.1.3 on 2021-01-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_property_financial_desclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='acquistion',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='acquistion_frequency',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='asset_management',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='asset_management_frequency',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
