# Generated by Django 3.1.3 on 2021-01-30 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210130_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='acquistion',
            new_name='acquisition',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='acquistion_frequency',
            new_name='acquisition_frequency',
        ),
    ]
