# Generated by Django 3.1.3 on 2021-01-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210130_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('day0', models.CharField(default=False, max_length=100)),
                ('year1', models.CharField(default=False, max_length=100)),
                ('year2', models.CharField(default=False, max_length=100)),
                ('year3', models.CharField(default=False, max_length=100)),
                ('year4', models.CharField(default=False, max_length=100)),
                ('year5', models.CharField(default=False, max_length=100)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
