# Generated by Django 3.1.3 on 2021-01-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_financialmodal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmodal',
            name='day0',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financialmodal',
            name='year1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financialmodal',
            name='year2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financialmodal',
            name='year3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financialmodal',
            name='year4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='financialmodal',
            name='year5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
