# Generated by Django 3.1.3 on 2021-01-31 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210130_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='application_detail',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='application_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='application_overview',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='sponsor_document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='experience_description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='experience_tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='experience_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sponsers'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
