# Generated by Django 3.1.3 on 2021-01-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210131_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='location',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='application_detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='application_overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='experience_description',
            field=models.TextField(),
        ),
    ]
