# Generated by Django 3.1.3 on 2021-01-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210131_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='asset_risk',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='asset_type',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='expected_holding_period',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='expected_irr',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='funded_member',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_investment',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='total_deal_size',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='total_sft',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
