# Generated by Django 3.1.3 on 2021-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='us_resident',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='residence_country',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
