# Generated by Django 3.1.3 on 2021-02-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_profile_us_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_us_resident',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ownership_type',
            field=models.CharField(choices=[('individual', 'INDIVIDUAL'), ('company', 'COMPANY TYPE')], default='individual', max_length=20),
        ),
    ]
