# Generated by Django 3.1.3 on 2021-02-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210209_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_us_resident',
            new_name='us_resident',
        ),
    ]
