# Generated by Django 3.1.3 on 2021-02-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210209_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='us_citizen',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=30),
        ),
    ]
