# Generated by Django 3.1.3 on 2021-02-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_profile_us_citizen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accreditation',
            field=models.CharField(choices=[(1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.')], default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='custodial_account',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='ssn_taxid',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default=False, max_length=30),
        ),
    ]
