# Generated by Django 3.1.3 on 2021-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210209_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='investment_experience',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=1, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='previously_invested',
            field=models.CharField(choices=[(1, 'Stocks'), (1, 'Mutual Funds'), (1, 'Bonds'), (1, 'Reits'), (1, 'Pvt. Equality'), (1, 'Venture Capital')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='accreditation',
            field=models.CharField(choices=[(1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), (6, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.')], default=1, max_length=30),
        ),
    ]
