# Generated by Django 3.1.3 on 2021-02-11 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20210209_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accreditation',
            field=models.CharField(choices=[('1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), ('2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), ('3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), ('4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), ('5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.'), ('6', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed dapibus lorem a ipsum egestas, a lacinia ligula condimentum.')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='custodial_account',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='investment_experience',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='previously_invested',
            field=models.CharField(choices=[('1', 'Stocks'), ('2', 'Mutual Funds'), ('3', 'Bonds'), ('4', 'Reits'), ('5', 'Pvt. Equality'), ('6', 'Venture Capital')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ssn_taxid',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='us_citizen',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProspectusDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('document', models.FileField(upload_to='prospectus/document')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.property')),
            ],
        ),
    ]
