# Generated by Django 3.1.3 on 2021-02-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_individualkyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualkyc',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='IndividualKyc'),
        ),
        migrations.AlterField(
            model_name='individualkyc',
            name='id_proof',
            field=models.ImageField(blank=True, upload_to='IndividualKyc'),
        ),
    ]
