# Generated by Django 3.1.3 on 2021-02-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210212_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualkyc',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='IndividualKyc'),
        ),
    ]
