# Generated by Django 3.1.3 on 2021-02-12 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_auto_20210212_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyKyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('social_channels', models.TextField()),
                ('hq', models.CharField(max_length=100)),
                ('team_size', models.CharField(max_length=50)),
                ('home_page', models.CharField(max_length=50)),
                ('source_of_funds', models.CharField(max_length=1000)),
                ('foundedDate', models.DateField()),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('accredited_doc', models.FileField(blank=True, null=True, upload_to='CompanyKyc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
