# Generated by Django 3.1.6 on 2021-03-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_processflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatUserSay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=250)),
                ('social_media', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn')], default='linkedin', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='asset_type',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('retailer', 'Retailer')], default='commercial', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='tags',
            field=models.CharField(choices=[('RESALE', 'RESALE'), ('FULLY FUNDED', 'FULLY FUNDED')], default='RESALE', max_length=30),
        ),
    ]
