# Generated by Django 3.1.6 on 2021-03-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20210326_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatusersay',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='whatUserSays'),
        ),
    ]
