# Generated by Django 3.1.6 on 2021-03-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_whatusersay_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatusersay',
            name='photo',
            field=models.ImageField(null=True, upload_to='whatUserSays'),
        ),
    ]
