# Generated by Django 3.1.6 on 2021-04-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20210326_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='faqtype',
            field=models.CharField(choices=[('general', 'GENERAL'), ('taxrelated', 'TAX RELATED'), ('nri', 'NRI RELATED')], default='general', max_length=20),
        ),
    ]
